### ISSUE TITLE
Data for tweet2vec notebook

### ISSUE THREAD

**Issue by anujgupta82** [nzw0301/keras-examples#8]
Can you share the data (./data/tweets.tsv) used in tweet2vec.ipynb ?

**Comment by nzw0301** [comment]
Thank you for your comments.
Unfortunately, I cannot do that since this data is my private tweet.

I show some example lines of `tweets.tsv` below:

```
“Sinatra Recipes - Models - Mongo” URL	16
“Python Tutorials for Beginners and Programmers | Codementor” URL	16
“Python Tutorials for Beginners and Programmers | Codementor” URL	7
```

Each line has a tweet text and one hashtag id, e.g.:

- `“Sinatra Recipes - Models - Mongo” URL`: tweet text.
- `16`: a hashtag id

And then, two fields are separated by `tab` character.
